name: Generate Snake

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate the snake
        uses: Platane/snk@master
        with:
          github_user_name: AnaTorresLoureiro
          gif_out_path: output/github-contribution-grid-snake.gif
          svg_out_path: output/github-contribution-grid-snake.svg

      - name: Show build status
        run: git status

      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add output/
          git commit -m "Update snake contributions" || echo "No changes to commit"
          git push origin output

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
